"""add_removed_by_creator_to_pool_participants

Revision ID: 5bedcb75c195
Revises: b2e4f6a8c0d1
Create Date: 2026-06-04 18:27:07.374754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bedcb75c195'
down_revision = 'b2e4f6a8c0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pool_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('removed_by_creator', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pool_participants', schema=None) as batch_op:
        batch_op.drop_column('removed_by_creator')

    # ### end Alembic commands ###
