"""initial schema

Revision ID: d129c90f03ee
Revises: 
Create Date: 2026-05-27 19:43:32.492302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd129c90f03ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_name', sa.String(length=12), nullable=True),
    sa.Column('team_type', sa.String(length=16), nullable=False),
    sa.Column('flag_code', sa.String(length=2), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_teams_name_active', ['name'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('google_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('picture_url', sa.String(length=512), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=False)
        batch_op.create_index('uq_user_email_active', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.create_index('uq_user_google_id_active', ['google_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('tournaments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('champion_team_id', sa.String(length=36), nullable=True),
    sa.Column('runner_up_team_id', sa.String(length=36), nullable=True),
    sa.Column('third_place_team_id', sa.String(length=36), nullable=True),
    sa.Column('top_scorer', sa.String(length=120), nullable=True),
    sa.Column('best_player', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['champion_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['runner_up_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['third_place_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_champion_team_id'), ['champion_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_runner_up_team_id'), ['runner_up_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_third_place_team_id'), ['third_place_team_id'], unique=False)
        batch_op.create_index('uq_tournament_name_year_active', ['name', 'year'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('pools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_name', sa.String(length=120), nullable=False),
    sa.Column('creator_user_id', sa.String(length=36), nullable=True),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('exact_score_points', sa.Integer(), nullable=False),
    sa.Column('outcome_points', sa.Integer(), nullable=False),
    sa.Column('one_team_goals_points', sa.Integer(), nullable=False),
    sa.Column('penalty_bonus_points', sa.Integer(), nullable=False),
    sa.Column('predict_champion', sa.Boolean(), nullable=False),
    sa.Column('champion_points', sa.Integer(), nullable=False),
    sa.Column('predict_runner_up', sa.Boolean(), nullable=False),
    sa.Column('runner_up_points', sa.Integer(), nullable=False),
    sa.Column('predict_third_place', sa.Boolean(), nullable=False),
    sa.Column('third_place_points', sa.Integer(), nullable=False),
    sa.Column('predict_top_scorer', sa.Boolean(), nullable=False),
    sa.Column('top_scorer_points', sa.Integer(), nullable=False),
    sa.Column('predict_best_player', sa.Boolean(), nullable=False),
    sa.Column('best_player_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pools_creator_user_id'), ['creator_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pools_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pools_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_pools_tournament_id'), ['tournament_id'], unique=False)
        batch_op.create_index('uq_pool_slug_active', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('stages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('stage_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stages_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stages_tournament_id'), ['tournament_id'], unique=False)
        batch_op.create_index('uq_stage_name_active', ['tournament_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.create_index('uq_stage_order_active', ['tournament_id', 'order'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('award_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pool_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('champion_team_id', sa.String(length=36), nullable=True),
    sa.Column('runner_up_team_id', sa.String(length=36), nullable=True),
    sa.Column('third_place_team_id', sa.String(length=36), nullable=True),
    sa.Column('top_scorer', sa.String(length=120), nullable=True),
    sa.Column('best_player', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['champion_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runner_up_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['third_place_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('award_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_award_predictions_champion_team_id'), ['champion_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_award_predictions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_award_predictions_runner_up_team_id'), ['runner_up_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_award_predictions_third_place_team_id'), ['third_place_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_award_predictions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_award_prediction_active', ['pool_id', 'user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('pool_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pool_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pool_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pool_participants_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pool_participants_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_pool_user_active', ['pool_id', 'user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('pool_prizes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pool_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('position BETWEEN 1 AND 3', name='ck_pool_prize_position_range'),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pool_prizes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pool_prizes_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('uq_pool_prize_position_active', ['pool_id', 'position'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('rounds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stage_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rounds_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('uq_round_number_active', ['stage_id', 'number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('tournament_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stage_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_groups_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_groups_stage_id'), ['stage_id'], unique=False)
        batch_op.create_index('uq_group_name_active', ['stage_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('round_id', sa.String(length=36), nullable=False),
    sa.Column('home_team_id', sa.String(length=36), nullable=True),
    sa.Column('away_team_id', sa.String(length=36), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('went_to_penalties', sa.Boolean(), nullable=False),
    sa.Column('penalty_winner_team_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(home_score IS NULL AND away_score IS NULL) OR (home_score IS NOT NULL AND away_score IS NOT NULL)', name='ck_match_scores_both_or_neither'),
    sa.CheckConstraint('away_score IS NULL OR away_score >= 0', name='ck_match_away_score_positive'),
    sa.CheckConstraint('home_score IS NULL OR home_score >= 0', name='ck_match_home_score_positive'),
    sa.CheckConstraint('home_team_id IS NULL OR away_team_id IS NULL OR home_team_id != away_team_id', name='ck_match_teams_differ'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['penalty_winner_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_away_team_id'), ['away_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_home_team_id'), ['home_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_penalty_winner_team_id'), ['penalty_winner_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('round_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('round_id', sa.String(length=36), nullable=False),
    sa.Column('pool_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('round_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_snapshots_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_snapshots_pool_id'), ['pool_id'], unique=False)
        batch_op.create_index('uq_snapshot_round_pool_active', ['round_id', 'pool_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('tournament_teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['tournament_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_teams_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_teams_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_teams_team_id'), ['team_id'], unique=False)
        batch_op.create_index('uq_tournament_team_active', ['tournament_id', 'team_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pool_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('predicted_home_score', sa.Integer(), nullable=False),
    sa.Column('predicted_away_score', sa.Integer(), nullable=False),
    sa.Column('predicts_penalties', sa.Boolean(), nullable=False),
    sa.Column('predicted_penalty_winner_team_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('predicted_away_score >= 0', name='ck_prediction_away_score_positive'),
    sa.CheckConstraint('predicted_home_score >= 0', name='ck_prediction_home_score_positive'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['predicted_penalty_winner_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_prediction_per_match_active', ['pool_id', 'user_id', 'match_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('round_snapshot_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('exact_scores', sa.Integer(), nullable=False),
    sa.Column('outcome_hits', sa.Integer(), nullable=False),
    sa.Column('knockout_points', sa.Integer(), nullable=False),
    sa.Column('award_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('points >= 0', name='ck_snapshot_entry_points_positive'),
    sa.CheckConstraint('position >= 1', name='ck_snapshot_entry_position_positive'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['round_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('round_snapshot_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_snapshot_entries_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_snapshot_entries_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_snapshot_entries_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_snapshot_entry_user_active', ['snapshot_id', 'user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('score_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('exact_score', sa.Boolean(), nullable=False),
    sa.Column('outcome_hit', sa.Boolean(), nullable=False),
    sa.Column('penalty_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('points >= 0', name='ck_score_entry_points_positive'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_entries_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('uq_score_entry_prediction_active', ['prediction_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_entries', schema=None) as batch_op:
        batch_op.drop_index('uq_score_entry_prediction_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_score_entries_deleted_at'))

    op.drop_table('score_entries')
    with op.batch_alter_table('round_snapshot_entries', schema=None) as batch_op:
        batch_op.drop_index('uq_snapshot_entry_user_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_round_snapshot_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_round_snapshot_entries_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_round_snapshot_entries_deleted_at'))

    op.drop_table('round_snapshot_entries')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index('uq_prediction_per_match_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_predictions_user_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_match_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_deleted_at'))

    op.drop_table('predictions')
    with op.batch_alter_table('tournament_teams', schema=None) as batch_op:
        batch_op.drop_index('uq_tournament_team_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_tournament_teams_team_id'))
        batch_op.drop_index(batch_op.f('ix_tournament_teams_group_id'))
        batch_op.drop_index(batch_op.f('ix_tournament_teams_deleted_at'))

    op.drop_table('tournament_teams')
    with op.batch_alter_table('round_snapshots', schema=None) as batch_op:
        batch_op.drop_index('uq_snapshot_round_pool_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_round_snapshots_pool_id'))
        batch_op.drop_index(batch_op.f('ix_round_snapshots_deleted_at'))

    op.drop_table('round_snapshots')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_matches_status'))
        batch_op.drop_index(batch_op.f('ix_matches_starts_at'))
        batch_op.drop_index(batch_op.f('ix_matches_round_id'))
        batch_op.drop_index(batch_op.f('ix_matches_penalty_winner_team_id'))
        batch_op.drop_index(batch_op.f('ix_matches_home_team_id'))
        batch_op.drop_index(batch_op.f('ix_matches_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_matches_away_team_id'))

    op.drop_table('matches')
    with op.batch_alter_table('tournament_groups', schema=None) as batch_op:
        batch_op.drop_index('uq_group_name_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_tournament_groups_stage_id'))
        batch_op.drop_index(batch_op.f('ix_tournament_groups_deleted_at'))

    op.drop_table('tournament_groups')
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_index('uq_round_number_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_rounds_deleted_at'))

    op.drop_table('rounds')
    with op.batch_alter_table('pool_prizes', schema=None) as batch_op:
        batch_op.drop_index('uq_pool_prize_position_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_pool_prizes_deleted_at'))

    op.drop_table('pool_prizes')
    with op.batch_alter_table('pool_participants', schema=None) as batch_op:
        batch_op.drop_index('uq_pool_user_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_pool_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_pool_participants_deleted_at'))

    op.drop_table('pool_participants')
    with op.batch_alter_table('award_predictions', schema=None) as batch_op:
        batch_op.drop_index('uq_award_prediction_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_award_predictions_user_id'))
        batch_op.drop_index(batch_op.f('ix_award_predictions_third_place_team_id'))
        batch_op.drop_index(batch_op.f('ix_award_predictions_runner_up_team_id'))
        batch_op.drop_index(batch_op.f('ix_award_predictions_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_award_predictions_champion_team_id'))

    op.drop_table('award_predictions')
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.drop_index('uq_stage_order_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index('uq_stage_name_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_stages_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_stages_deleted_at'))

    op.drop_table('stages')
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.drop_index('uq_pool_slug_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_pools_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_pools_slug'))
        batch_op.drop_index(batch_op.f('ix_pools_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_pools_creator_user_id'))

    op.drop_table('pools')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index('uq_tournament_name_year_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_tournaments_third_place_team_id'))
        batch_op.drop_index(batch_op.f('ix_tournaments_runner_up_team_id'))
        batch_op.drop_index(batch_op.f('ix_tournaments_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_tournaments_champion_team_id'))

    op.drop_table('tournaments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('uq_user_google_id_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index('uq_user_email_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))

    op.drop_table('users')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index('ix_teams_name_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_teams_deleted_at'))

    op.drop_table('teams')
    # ### end Alembic commands ###
